-- MySQL Script generated by MySQL Workbench
-- Fri Sep  5 17:58:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oandm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oandm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oandm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `oandm` ;

-- -----------------------------------------------------
-- Table `oandm`.`dependencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oandm`.`dependencies` (
  `idDependency` INT NOT NULL,
  `DependencyName` VARCHAR(45) NULL,
  `Addres` VARCHAR(255) NULL,
  `RefStreet` VARCHAR(255) NULL,
  `Municipality` VARCHAR(45) NULL,
  `NroBuildDepLevels` INT NULL,
  PRIMARY KEY (`idDependency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oandm`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oandm`.`providers` (
  `idProviders` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Manager` VARCHAR(45) NULL,
  `Description` TEXT NULL,
  `providerscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idProviders`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oandm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oandm`.`users` (
  `iduser` INT NOT NULL,
  `UserName` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NULL,
  `Role` VARCHAR(255) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `MaintGroup` VARCHAR(45) NULL,
  `Provider` VARCHAR(45) NULL,
  `SubProvider` VARCHAR(45) NULL,
  `providers_idProviders` INT NOT NULL,
  `providers_idProviders1` INT NOT NULL,
  PRIMARY KEY (`iduser`, `providers_idProviders`),
  INDEX `fk_users_providers1_idx` (`providers_idProviders1` ASC) VISIBLE,
  CONSTRAINT `fk_users_providers1`
    FOREIGN KEY (`providers_idProviders1`)
    REFERENCES `oandm`.`providers` (`idProviders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oandm`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oandm`.`Tasks` (
  `idPrevMaint` INT NOT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `StartTime` TIME NULL DEFAULT NULL,
  `EndTime` TIME NULL DEFAULT NULL,
  `DependencyName` VARCHAR(255) NULL DEFAULT NULL,
  `Floor` INT NULL DEFAULT NULL,
  `MaintCategory` VARCHAR(45) NULL DEFAULT NULL,
  `MainTtype` VARCHAR(45) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `MaintGroup` TEXT NULL DEFAULT NULL,
  `MaintAdmin` VARCHAR(255) NULL DEFAULT NULL,
  `Municipality` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Region` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Provider` VARCHAR(45) NULL DEFAULT NULL,
  `Subprovider` VARCHAR(45) NULL DEFAULT NULL,
  `MaintRecord` TINYINT NULL,
  `dependencies_idDependency` INT NOT NULL,
  `users_iduser` INT NOT NULL,
  `users_providers_idProviders` INT NOT NULL,
  PRIMARY KEY (`idPrevMaint`),
  INDEX `fk_Tasks_dependencies1_idx` (`dependencies_idDependency` ASC) VISIBLE,
  INDEX `fk_Tasks_users1_idx` (`users_iduser` ASC, `users_providers_idProviders` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_dependencies1`
    FOREIGN KEY (`dependencies_idDependency`)
    REFERENCES `oandm`.`dependencies` (`idDependency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_users1`
    FOREIGN KEY (`users_iduser` , `users_providers_idProviders`)
    REFERENCES `oandm`.`users` (`iduser` , `providers_idProviders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
